MUNICIPALITY = {"code": "4127965", "name": "Turvo", "state": "PR"}
MODULES = [
    "Visão Geral",
    "Demografia",
    "Economia",
    "Finanças Públicas",
    "Saúde",
    "Educação",
    "Emprego",
    "Saneamento/Infraestrutura",
    "Compras Públicas/PNCP",
    "Transferências/convênios",
    "Comparação",
    "Escritório de Compras Públicas",
    "Fontes",
]
SOURCES = {
    "ibge": {
        "name": "IBGE / SIDRA",
        "url": "https://sidra.ibge.gov.br",
        "description": "Estatísticas municipais, Censo e PIB. Períodos e unidades preservados da resposta oficial.",
    },
    "siconfi": {
        "name": "Tesouro Nacional / SICONFI",
        "url": "https://apidatalake.tesouro.gov.br/docs/siconfi/",
        "description": "RREO, anexo 03. O ano e bimestre da declaração não são a data da coleta.",
    },
    "cnes": {
        "name": "Ministério da Saúde / CNES",
        "url": "https://cnes.datasus.gov.br",
        "description": "Estabelecimentos ativos. Competência nem sempre informada pela API; sem totais nacionais de leitos.",
    },
    "fnde": {
        "name": "FNDE / PNAE",
        "url": "https://www.gov.br/fnde/pt-br/acesso-a-informacao/dados-abertos",
        "description": "Alunos atendidos, desagregados por etapa e esfera. Endpoint documentado até 2022.",
    },
    "inep": {
        "name": "INEP",
        "url": "https://www.gov.br/inep/pt-br/acesso-a-informacao/dados-abertos",
        "description": "Resultados oficiais do IDEB por município, etapa e rede, processados a partir das planilhas do INEP.",
    },
    "rais": {
        "name": "Ministério do Trabalho / RAIS",
        "url": "https://www.gov.br/trabalho-e-emprego/pt-br/assuntos/estatisticas-trabalho",
        "description": "Sem conector RAIS no MCP inspecionado. Ingestão suplementar de agregados oficiais validada por território e proveniência.",
    },
    "pncp": {
        "name": "PNCP",
        "url": "https://pncp.gov.br/api/consulta/swagger-ui/index.html",
        "description": "Contratações publicadas, todas as modalidades, órgão por CNPJ. Valores estimados não são despesas pagas.",
    },
    "transferegov": {
        "name": "TransfereGov",
        "url": "https://api-publica.transferegov.gestao.gov.br/parcerias/docs",
        "description": "API aberta de Gestão de Parcerias, além dos dados de transferências especiais. Convênios e emendas especiais são indicadores separados.",
    },
    "rfb": {
        "name": "Receita Federal / CNPJ",
        "url": "https://www.gov.br/receitafederal/pt-br/acesso-a-informacao/dados-abertos/cadastros",
        "description": "Cadastro aberto contém município, CNAE, porte e opção SIMEI. O retrato municipal agregado requer processamento do conjunto nacional; nenhuma listagem identificável é publicada.",
    },
    "sebrae": {
        "name": "Sebrae/PR • IDAN-M",
        "url": "https://sebraepr.com.br/servicos/premio-cidade-empreendedora/",
        "description": "Índice anual de Desenvolvimento do Ambiente de Negócios Municipal. Resultados públicos encontrados são divulgações e reconhecimentos; não foi localizada API ou planilha municipal aberta com a série completa de Turvo.",
    },
}


def indicator(id, title, module, source, unit, method, tool=None, args=None, note=""):
    return dict(
        id=id,
        title=title,
        module=module,
        source=source,
        unit=unit,
        method=method,
        tool=tool,
        args=args or {},
        note=note,
    )


CATALOG = [
    indicator(
        "population",
        "População estimada",
        "Demografia",
        "ibge",
        "pessoas",
        "Série anual de estimativas; não interpolar anos de Censo.",
        "observatorio_ibge",
        {"agregado": 6579, "variavel": 9324},
    ),
    indicator(
        "area",
        "Área territorial",
        "Demografia",
        "ibge",
        "km²",
        "Área oficial municipal em km².",
        "observatorio_ibge",
        {"agregado": 1301, "variavel": 615},
    ),
    indicator(
        "gdp",
        "PIB municipal",
        "Economia",
        "ibge",
        "R$",
        "PIB a preços correntes. Conversão de mil reais para reais.",
        "observatorio_ibge",
        {"agregado": 5938, "variavel": 37},
    ),
    indicator(
        "gdp_per_capita",
        "PIB por habitante • calculado",
        "Economia",
        "ibge",
        "R$",
        "PIB municipal dividido pela população estimada, no último ano comum às duas séries. Não equivale ao PIB per capita oficial quando a base populacional difere.",
        "observatorio_pib_por_habitante",
    ),
    indicator(
        "literacy",
        "Alfabetização • 15 anos ou mais",
        "Educação",
        "ibge",
        "%",
        "Censo 2022, total de sexo, cor/raça e idade.",
        "observatorio_ibge",
        {"agregado": 9543, "variavel": 2513, "classificacao": "2[6794]|86[95251]|287[100362]"},
    ),
    indicator(
        "sewage",
        "Domicílios ligados à rede de esgoto/pluvial",
        "Saneamento/Infraestrutura",
        "ibge",
        "%",
        "Tabela 6805, categoria 46290: inclui rede geral, pluvial ou fossa ligada à rede. Não equivale a esgoto tratado.",
        "observatorio_ibge",
        {"agregado": 6805, "variavel": 1000381, "classificacao": "11558[46290]"},
    ),
    indicator(
        "rcl",
        "Receita corrente líquida",
        "Finanças Públicas",
        "siconfi",
        "R$",
        "RREO Anexo 03, RCL (III), coluna TOTAL (ÚLTIMOS 12 MESES). Sem somar receitas componentes.",
        "observatorio_fiscal",
    ),
    indicator(
        "health_units",
        "Estabelecimentos de saúde ativos",
        "Saúde",
        "cnes",
        "unidades",
        "Contagem por CNES único, território validado e todas as páginas.",
        "observatorio_cnes",
        note="Competência não informada pela API. O horário da coleta não substitui o período da fonte.",
    ),
    indicator(
        "pnae",
        "Alunos atendidos pelo PNAE",
        "Educação",
        "fnde",
        "alunos",
        "Registros FNDE por esfera/etapa, território exato. Não somar linhas sem validação de sobreposição.",
        "observatorio_pnae",
        {"ano": 2022},
    ),
    indicator(
        "ideb",
        "IDEB municipal",
        "Educação",
        "inep",
        "índice",
        "Resultados municipais do INEP, separados por etapa e rede. Não misturar escolas, municípios e estado.",
        "observatorio_ideb",
        {"ano": 2023},
    ),
    indicator(
        "formal_jobs",
        "Vínculos formais • RAIS",
        "Emprego",
        "rais",
        "vínculos",
        "Estoque em 31/12, município do estabelecimento. Apenas agregados oficiais, sem microdados pessoais.",
        note="Sem ferramenta RAIS na versão inspecionada. Aceita importação suplementar documentada de agregados oficiais.",
    ),
    indicator(
        "procurement",
        "Contratações publicadas no PNCP",
        "Compras Públicas/PNCP",
        "pncp",
        "processos",
        "Identificadores PNCP únicos por CNPJ municipal, ano de publicação e todas as modalidades/páginas.",
        "observatorio_pncp",
    ),
    indicator(
        "procurement_contracts",
        "Contratos publicados no PNCP",
        "Escritório de Compras Públicas",
        "pncp",
        "contratos",
        "Contratos e empenhos publicados por órgãos municipais no PNCP, com filtros por período, categoria e tipo de fornecedor. Valores registrados não equivalem a pagamentos.",
        "observatorio_pncp_contratos",
        note="Dados fiscais ou pessoais de fornecedores não são exibidos. O porte MEI/ME/EPP depende de campo confiável do cadastro da fonte.",
    ),
    indicator(
        "business_profile",
        "Empresas ativas por porte e atividade econômica",
        "Escritório de Compras Públicas",
        "rfb",
        "empresas",
        "Agregação municipal da base aberta CNPJ por MEI, ME, EPP, demais portes, CNAE e situação ativa.",
        note="A base nacional da Receita Federal exige processamento mensal; este indicador só será publicado após carga completa e validada. O retrato não identifica empresas.",
    ),
    indicator(
        "idan_m",
        "IDAN-M • Sebrae/PR",
        "Escritório de Compras Públicas",
        "sebrae",
        "pontos (0–100)",
        "Pontuação anual oficial do Índice de Desenvolvimento do Ambiente de Negócios Municipal, conforme divulgação ou extrato oficial do Sebrae/PR. O índice é acompanhado nos municípios participantes do Cidade Empreendedora; não estimar a nota a partir dos eixos.",
        note="Série de Turvo ainda não localizada em API ou tabela pública estruturada. A publicação exige extrato ou divulgação oficial do Sebrae/PR e validação do ano e município. Consulte a página de fontes para os canais públicos.",
    ),
    indicator(
        "transfers",
        "Planos de transferências especiais",
        "Transferências/convênios",
        "transferegov",
        "planos",
        "Planos de ação únicos para o CNPJ da Prefeitura. Sem inferir valor pago.",
        "observatorio_transferencias",
    ),
    indicator(
        "agreements",
        "Propostas federais de parceria",
        "Transferências/convênios",
        "transferegov",
        "propostas",
        "Propostas cadastradas para o município na API Gestão de Parcerias. Não significa convênio assinado, valor transferido ou pagamento.",
        "observatorio_parcerias",
        {"ano": 2025},
        note="O painel identifica propostas; uma parceria celebrada é uma etapa posterior. Valores propostos não são valores transferidos ou pagos.",
    ),
]
