MUNICIPALITY = {"code": "4127965", "name": "Turvo", "state": "PR"}
MODULES = [
    "Visão Geral",
    "Demografia",
    "Economia",
    "Finanças Públicas",
    "Saúde",
    "Educação",
    "Emprego",
    "Saneamento/Infraestrutura",
    "Compras Públicas/PNCP",
    "Transferências/convênios",
    "Comparação",
    "Fontes",
]
SOURCES = {
    "ibge": {
        "name": "IBGE / SIDRA",
        "url": "https://sidra.ibge.gov.br",
        "description": "Estatísticas municipais, Censo e PIB. Períodos e unidades preservados da resposta oficial.",
    },
    "siconfi": {
        "name": "Tesouro Nacional / SICONFI",
        "url": "https://apidatalake.tesouro.gov.br/docs/siconfi/",
        "description": "RREO, anexo 03. O ano e bimestre da declaração não são a data da coleta.",
    },
    "cnes": {
        "name": "Ministério da Saúde / CNES",
        "url": "https://cnes.datasus.gov.br",
        "description": "Estabelecimentos ativos. Competência nem sempre informada pela API; sem totais nacionais de leitos.",
    },
    "fnde": {
        "name": "FNDE / PNAE",
        "url": "https://www.gov.br/fnde/pt-br/acesso-a-informacao/dados-abertos",
        "description": "Alunos atendidos, desagregados por etapa e esfera. Endpoint documentado até 2022.",
    },
    "inep": {
        "name": "INEP",
        "url": "https://www.gov.br/inep/pt-br/acesso-a-informacao/dados-abertos",
        "description": "Catálogo de microdados disponível no MCP; IDEB municipal exige processamento adicional, não confundir com IDEB estadual.",
    },
    "rais": {
        "name": "Ministério do Trabalho / RAIS",
        "url": "https://www.gov.br/trabalho-e-emprego/pt-br/assuntos/estatisticas-trabalho",
        "description": "Sem conector RAIS no MCP inspecionado. Ingestão suplementar de agregados oficiais validada por território e proveniência.",
    },
    "pncp": {
        "name": "PNCP",
        "url": "https://pncp.gov.br/api/consulta/swagger-ui/index.html",
        "description": "Contratações publicadas, todas as modalidades, órgão por CNPJ. Valores estimados não são despesas pagas.",
    },
    "transferegov": {
        "name": "TransfereGov",
        "url": "https://www.gov.br/transferegov/pt-br",
        "description": "Transferências especiais (emendas Pix), por CNPJ. Planos de ação não representam pagamentos nem todos os convênios.",
    },
}


def indicator(id, title, module, source, unit, method, tool=None, args=None, note=""):
    return dict(
        id=id,
        title=title,
        module=module,
        source=source,
        unit=unit,
        method=method,
        tool=tool,
        args=args or {},
        note=note,
    )


CATALOG = [
    indicator(
        "population",
        "População estimada",
        "Demografia",
        "ibge",
        "pessoas",
        "Série anual de estimativas; não interpolar anos de Censo.",
        "observatorio_ibge",
        {"agregado": 6579, "variavel": 9324},
    ),
    indicator(
        "area",
        "Área territorial",
        "Demografia",
        "ibge",
        "km²",
        "Área oficial municipal em km².",
        "observatorio_ibge",
        {"agregado": 1301, "variavel": 615},
    ),
    indicator(
        "gdp",
        "PIB municipal",
        "Economia",
        "ibge",
        "R$",
        "PIB a preços correntes. Conversão de mil reais para reais.",
        "observatorio_ibge",
        {"agregado": 5938, "variavel": 37},
    ),
    indicator(
        "gdp_per_capita",
        "PIB por habitante • calculado",
        "Economia",
        "ibge",
        "R$",
        "PIB municipal dividido pela população estimada, no último ano comum às duas séries. Não equivale ao PIB per capita oficial quando a base populacional difere.",
        "observatorio_pib_por_habitante",
    ),
    indicator(
        "literacy",
        "Alfabetização • 15 anos ou mais",
        "Educação",
        "ibge",
        "%",
        "Censo 2022, total de sexo, cor/raça e idade.",
        "observatorio_ibge",
        {"agregado": 9543, "variavel": 2513, "classificacao": "2[6794]|86[95251]|287[100362]"},
    ),
    indicator(
        "sewage",
        "Domicílios ligados à rede de esgoto/pluvial",
        "Saneamento/Infraestrutura",
        "ibge",
        "%",
        "Tabela 6805, categoria 46290: inclui rede geral, pluvial ou fossa ligada à rede. Não equivale a esgoto tratado.",
        "observatorio_ibge",
        {"agregado": 6805, "variavel": 1000381, "classificacao": "11558[46290]"},
    ),
    indicator(
        "rcl",
        "Receita corrente líquida",
        "Finanças Públicas",
        "siconfi",
        "R$",
        "RREO Anexo 03, RCL (III), coluna TOTAL (ÚLTIMOS 12 MESES). Sem somar receitas componentes.",
        "observatorio_fiscal",
    ),
    indicator(
        "health_units",
        "Estabelecimentos de saúde ativos",
        "Saúde",
        "cnes",
        "unidades",
        "Contagem por CNES único, território validado e todas as páginas.",
        "observatorio_cnes",
        note="Competência não informada pela API. O horário da coleta não substitui o período da fonte.",
    ),
    indicator(
        "pnae",
        "Alunos atendidos pelo PNAE",
        "Educação",
        "fnde",
        "alunos",
        "Registros FNDE por esfera/etapa, território exato. Não somar linhas sem validação de sobreposição.",
        "observatorio_pnae",
        {"ano": 2022},
    ),
    indicator(
        "ideb",
        "IDEB municipal",
        "Educação",
        "inep",
        "índice",
        "Processar microdados municipais por rede e etapa antes da publicação.",
        note="Conector municipal de microdados ainda não homologado; o MCP disponibiliza catálogo e downloads.",
    ),
    indicator(
        "formal_jobs",
        "Vínculos formais • RAIS",
        "Emprego",
        "rais",
        "vínculos",
        "Estoque em 31/12, município do estabelecimento. Apenas agregados oficiais, sem microdados pessoais.",
        note="Sem ferramenta RAIS na versão inspecionada. Aceita importação suplementar documentada de agregados oficiais.",
    ),
    indicator(
        "procurement",
        "Contratações publicadas no PNCP",
        "Compras Públicas/PNCP",
        "pncp",
        "processos",
        "Identificadores PNCP únicos por CNPJ municipal, ano de publicação e todas as modalidades/páginas.",
        "observatorio_pncp",
    ),
    indicator(
        "transfers",
        "Planos de transferências especiais",
        "Transferências/convênios",
        "transferegov",
        "planos",
        "Planos de ação únicos para o CNPJ da Prefeitura. Sem inferir valor pago.",
        "observatorio_transferencias",
    ),
    indicator(
        "agreements",
        "Convênios federais",
        "Transferências/convênios",
        "transferegov",
        "convênios",
        "Não confundir transferências especiais com convênios.",
        note="O conector MCP atual cobre transferências especiais; convênios dependem de integração complementar homologada.",
    ),
]
